[tools]
go = "1.24"
java = "21"
node = "22"

python = "3.13"
uv = "latest"

"cargo:cargo-binstall" = "latest"
"cargo:rustic-rs" = "latest"

"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:jdx/usage" = "latest"

[env]
MISE_DATA_DIR = "{{env.HOME}}/.local/share/mise"

#_.python.venv = { path = "{{env.MISE_DATA_DIR}}/python/venv/global", create = true }

[settings]
python.uv_venv_auto = true
# use provided binaries if available
cargo.binstall = true
experimental = true
